### ISSUE TITLE
Option to create a local incremental backup based on a full local backup

### ISSUE THREAD

**Issue by lesandie** [Altinity/clickhouse-backup#1054]
We can create an incremental that will diff from a remote full backup like this:

 ```bash
clickhouse-backup create --tables=keylogger.\* --diff-from-remote keylogger_full keylogger_inc1
```
https://github.com/Altinity/clickhouse-backup#cli-command---create

The  keylogger_full was already uploaded to s3. 

Also what you can do is create a remote/upload incremental backup based on a local one: 

```bash
clickhouse-backup create_remote/upload --tables=keylogger.\* --diff-from keylogger_full keylogger_inc1
```
https://github.com/Altinity/clickhouse-backup#cli-command---create_remote

What we don't have is to create an incremental local backup from a full local backup like this:

```bash
clickhouse-backup create --tables=keylogger.\* --diff-from keylogger_full keylogger_inc1
```

@Slach do you think this is a good idea?. There are some use cases that could benefit from this.

**Comment by Slach** [comment]
just for search engines

`--diff-from` and `--diff-from-remote` actually parameters for upload command, not for `create`
cause increment calculates only during `upload`

we added `--diff-from-remote` parameter into `create` command for `use_embedded_backup: true` and for object disk data parts upload

`create --diff-from` have no sense because local backup is just a set of hard links and don't allocate disk space until the original data files deleted
