### ISSUE TITLE
Improve performance for restore remote backup

### ISSUE THREAD

**Issue by dborovtsov** [Altinity/clickhouse-backup#142]
Hi Alex

 thnx for great tool, its very useful for automating backup procedure. It works well and easy to use.
 Recently I had experience of restoring database from remote backup, file size was ~1.5Tb  and process took too much time due to 
1. Download speed.  Looks like download process is single thread and I had to manually download archive using "gsutil" to make it faster.
2. Extract speed.  There is no way to extract tgz files with multiply threads. "pigz" tool improves situation a little bit but this process is still very slow.

Is it possible to add following features
1. Parallel download from GCS ( S3? )
    Some details available [here](https://medium.com/@duhroach/gcs-read-performance-of-large-files-bd53cfca4410)
2. Add another compression algo for GCS that supports multi thread decompression (lz4, xz, bzip2).  They are supported for S3 but not for GCS.

**Comment by AlexAkulov** [comment]
Hi @dborovtsov! 
Thank you for detailed description and useful links! 

1. Accelerating large files downloading by http ranges described in this article is very interesting. I think this approach can be very useful for clickhouse-backup.
2. Parallel gzip is already used in clickhouse-backup since [v0.4.1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v0.4.1). But using compression can reduce performance in many cases. ClickHouse has already been storing data in compressed format for a long time and GCS already compresses data by gzip on transferring too. You can disable compressing in clickhouse-backup by setting option `gcs.compression_format: tar` in config file and you can compare results.

Now I'm focused on v1.0.0 witch will contain support of Atomic databases and Tires Storages. After that I can do researching of improvement of download/upload performance. 
(Related links for s3 https://github.com/peak/s5cmd)

**Comment by Slach** [comment]
@dborovtsov could you try to https://github.com/Altinity/clickhouse-backup/releases/tag/1.0.16?
this release support go routines pool during download and upload

**Comment by Slach** [comment]
Look like issue resolved after release 1.0.16
