### ISSUE TITLE
Backup clarification

### ISSUE THREAD

**Issue by andrii29** [Altinity/clickhouse-backup#34]
Hello,
I have few questions about backup.
Before I used _v0.2.0_ with archive strategy and full backup.
Today I tried _v0.3.4_.

1. Is there any command to delete old backups from **clickhouse_folder/backup**?
2. Is there any command to delete old backups from s3?
3. I used command  "`clickhouse-backup upload backup_name`" (_v0.3.4_). This command deleted all my old backups from s3. WTF?)
4. Do I need to keep old backups locally to  use incremental backup (`--diff-from=<old_backup_name>`) ?
5.  _v0.3.2_ DEPREСATIONS: 'dry-run' flag and 'archive' strategy were marked as deprecated
Why 'archive' strategy were marked as deprecated?

Regards,
Andrii.

**Comment by AlexAkulov** [comment]
Hello Andrii!
1. You can use **rm -rf clickhouse_folder/bakup** for deleting specific local backup. clickhouse-backup will remove old local backups after you run 'create' command if you have defined option `backups_to_keep_local` in config file.
2. You can use s3cmd or similar tools for deleting backups from s3. clickhouse-backup will remove old backups from s3 after you run 'upload' command if you have defined option `backups_to_keep_s3` in config file.
3. It can happen if option `backups_to_keep_s3` is set to 1. By default this option is set to 0 that means backups are never deleted.
4. Yes. You need to keep two local backups in order to be able to upload differences only. For example: if you have uploaded backup for Monday, and want to upload diff for Tuesday run `clickhouse-backup upload --diff-from=moday tuesday`. On Wednesday you can remove local backup for Monday and upload diff between Tuesday and Wednesday.
5. It is a mistake! Of course 'tree' strategy was deprecated. I fixed it in the release message. Thank you!

**Comment by andrii29** [comment]
Hello,
Thank You for reply.
1. Is it possible to add delete and delete_s3 commands to manage old backups "by hands" with this tool? 
2. It would be cool to update "list" command. For example, I want to list only last (or first) local backup name and use output with another command

Regards,
Andrii.

**Comment by AlexAkulov** [comment]
I added 'delete' command and improve 'list' here https://github.com/AlexAkulov/clickhouse-backup/commit/0e4f1285800585efe2959bdcfacb78c9dc08ff81
Now you can use output of list command like this:
Create backup and uploading diff:
```
# clickhouse-backup create
# clickhouse-backup upload --diff-from=$(clickhouse-backup list local penult) $(clickhouse-backup list local latest)
```
Remove backups:
```
clickhouse-backup delete local <backup_name>
clickhouse-backup delete s3 $(clickhouse-backup list s3 latest)
```

**Comment by andrii29** [comment]
@AlexAkulov Hello,
Thank You very much!
Please create new release for this changes.

Regards,
Andrii.
