### ISSUE TITLE
clickhouse-backup server supports http synced response.

### ISSUE THREAD

**Issue by wangzhen11aaa** [Altinity/clickhouse-backup#364]

**Comment by Slach** [comment]
Sync API is not usable for most use cases

just try to think about upload 1TB data (couple of hours)
current api implementation is enough

**Comment by wangzhen11aaa** [comment]
Yes, that's a  problem.

**Comment by Slach** [comment]
> Yes, that's a problem.

What problem do you mean?

As I said, if you try to think a bit more, you will agree with `create / upload, download / restrore` operations are asynchronous by design and can't be called via SYNC API, cause can take unpredictable time.

Current workflow:
1. fire operation via `POST /backup/actions` (/backup/create etc.), 
2. poll status of operation via `GET /backup/actions?filter="<command>"`

**Comment by wangzhen11aaa** [comment]
> > Yes, that's a problem.
> 
> What problem do you mean?
> 
> As I said, if you try to think a bit more, you will agree with `create / upload, download / restrore` operations are asynchronous by design and can't be called via SYNC API, cause can take unpredictable time.
> 
> Current workflow:
> 
> 1. fire operation via `POST /backup/actions` (/backup/create etc.),
> 2. poll status of operation via `GET /backup/actions?filter="<command>"`

I agree that. :)
