### ISSUE TITLE
Support for Google Cloud Storage

### ISSUE THREAD

**Issue by teralype** [Altinity/clickhouse-backup#46]
Support for native Google Cloud Storage is desirable. I am talking about native Google Cloud API, and not the interoperability API that Googles provides. See https://cloud.google.com/storage/docs/migrating for additional information.

**Comment by AlexAkulov** [comment]
Feel free to send PRs!

**Comment by przemekd** [comment]
I might implement this one.

**Comment by przemekd** [comment]
@AlexAkulov I've added a draft of the solution -> https://github.com/AlexAkulov/clickhouse-backup/pull/54 <- may you look at it? It contains a lot of duplicated code - would you like me to create shared interface for S3 and GCS?

What about command line parameters? How would you like to solve it? What do you think about my solution?

**Comment by AlexAkulov** [comment]
@przemekd Good work!
1. I think shared interface for cloud providers will be good solution. It allows to add other remote storages like 'Swift' or 'Ceph' in future simpler.
2. Why are credentials located in separated file? Maybe it would be more convenient if all settings including credentials will be contained in one file, like it's made for s3?
3. In many cases people use one of the cloud providers and it's not necessary to define it every time. I think selection of the remote storage must be as option in config file like `remote_storage: gce # s3` instead of flags '--dest=<gcs|aws>'. Then you will use just 'clickhouse-backup upload` without additional params. If you want to switch remote storage once you can override it via env like  ``` REMOTE_STORAGE=s3 clickhouse-backup upload```

**Comment by przemekd** [comment]
1. Ok, let me create a shared interface.
2. Google credentials are in the form of a rather lengthy JSON file and putting JSON directly into a YAML variable is definitely not pretty. What about providing both ways, one could either use separated JSON file or put credentials directly in YAML config?
3. Yeah, I'll add `remote_storage` var and use `s3` as default value.

**Comment by AlexAkulov** [comment]
Ok. Thank you!

**Comment by yuzhichang** [comment]
@AlexAkulov I desire the support for HDFS. Does the shared interface fit HDFS?

**Comment by przemekd** [comment]
@AlexAkulov I've created a `BackupDestination` abstraction and made some other changes. Do you have any comments on that? 
@yuzhichang it should be possible to implement support for HDFS as well.

**Comment by AlexAkulov** [comment]
@przemekd How about removing old backups after uploading? I see this code has been commented out.

**Comment by przemekd** [comment]
@AlexAkulov That's my error, I missed that part during refactoring.  I've already fixed it.

**Comment by AlexAkulov** [comment]
@przemekd Thank you very much! I will add integration tests with GSC and create release.

**Comment by AlexAkulov** [comment]
Done in https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v0.5.0
