### ISSUE TITLE
Error during restore incremental backup already exists after 1 times, please check your schema dependencies

### ISSUE THREAD

**Issue by gawsoftpl** [Altinity/clickhouse-backup#470]
## Error overview
During restoring incremental backup I received error:

error can't create table `backup`.`uk_price_paid`: code: 57, message: Directory for table data store/2b3/2b3925e0-1b41-466f-85ae-228765bc2c6c/ already exists after 1 times, please check your schema dependencies

It happened due to UUID collision, most likely because some not random UUIDs were manually specified in CREATE queries. after 1 times, please check your schema dependencies

## How to resolve
1. restart database server
2. restore only schema with --rm 
```sh
clickhouse-backup restore -rm -s backup3
```
3. restore only data
```sh
clickhouse-backup restore -d backup3
```

**Comment by Slach** [comment]
looks like it expected behavior, and not accroding to "incremental" backup
if you try to restore on server where table already exits with the same UUID, you will see this error

During execute `clickhouse-backup create` UUID inherited from create table definition `backup.uk_price_paid` on source server
