### ISSUE TITLE
All backups are removed when reach the keep_remote variable

### ISSUE THREAD

**Issue by cobak78** [Altinity/clickhouse-backup#512]
Hi, 
I found an issue with the s3 backups management. Whenever it reaches the keep remote variable then deletes all the S3 backups generated.

I think the issue is related to S3_PATH variable, as i tested without setting that variable and the keep_remote function works. I'm taking a look at the code to see if I can find the issue, but any guide will be very appreciated.

**Comment by Slach** [comment]
Sorry, I know nothing `keep_remote`
could you clarify?
Do you mean you changed `S3_PATH` and `KEEP_BACKUPS_REMOTE` variables, and after it list remote backups is empty?

**Comment by cobak78** [comment]
No, i did not change S3_PATH variable. If is set and KEEP_BACKUPS_REMOTE is also set, when it gets to that number of backups, deletes all the backups stored in S3.

With this configuration:

```
- name: BACKUPS_TO_KEEP_REMOTE
          value: '9'
- name: S3_BUCKET
          value: /backups/
- name: S3_PATH
          value: /foo/bar/
```

Deletes all backups when it gets to 9.

With this configuration:
```
- name: BACKUPS_TO_KEEP_REMOTE
          value: '9'
- name: S3_BUCKET
          value: /backups/
- name: S3_PATH
          value: /
```
works as expected and start deleting backups and keep always nine in S3

**Comment by Slach** [comment]
could you add
```yaml
- name: LOG_LEVEL
   value: debug
```

to your clickhouse-backup container `env` where `S3_PATH` value /foo/back, deploy new manifest to kubernetes
  
and after it run
`kubectl exec -n <your_namespace> <your-clickhouse-backup-pod-name> -c clickhouse-backup -- clickhouse-backup create_remote test_backup`

And share the results?

usually S3_BUCKET is just a name without slashes, S3_BUCKET with `value: backups` instead of `/backups/` is more proper value

**Comment by cobak78** [comment]
you were right.
it works without the slashes in the S3_BUCKET
Thanks!
