### ISSUE TITLE
simplify cmd line

### ISSUE THREAD

**Issue by dcastanier** [Altinity/clickhouse-backup#53]
It's could be nice to simplify cmd line to allow backup or restore in a single line.
for example:
- backup (create + upload)
- restore (download + restore-schema + restore-data)
or allow multiple command per line.

**Comment by AlexAkulov** [comment]
You can do it in the following ways
1. Create bash script
```
#!/bin/bash
set -e
set -x
BACKUP_NAME=my_backup_$(date -u +%Y-%m-%dT%H-%M-%S)
clickhouse-backup create $BACKUP_NAME
clickhouse-backup upload $BACKUP_NAME
```

```
#!/bin/bash
# download + restore-schema + restore-data
set -e
set -x
clickhouse-backup download $1
clickhouse-backup restore-schema $1
clickhouse-backup restore-data $1
```
2. Use cmd
```
clickhouse-backup create && \
clickhouse-backup upload $(clickhouse-backup list local latest)
```

```
BACKUP=$(clickhouse-backup list s3 latest | cut -d. -f1) \
clickhouse-backup download $BACKUP && \
clickhouse-backup restore-schema $BACKUP && \
clickhouse-backup restore-data $BACKUP
```

I think it is enough simple. Do you have any ideas how to make it more simple?

**Comment by dcastanier** [comment]
I understand the current state, and the documentation is clear.
With overloading entrypoint, I use the second way with the standard docker image.

To clarify the proposition of refactoring, the list of commands could be:

1. table : like currently
1. list : like currently
1. delete : like currently
1. default-config : like currently
1. backup [-t, --tables=< db>.< table>] <backup_name>
   - new command that do : clean, create, upload by default. 
   - Flags allow to skip some parts:
   - --skip-clean
   - --skip-create
   - --skip-upload
   - --diff-from=penult | <backup_name>
1. restore [-t, --tables=< db>.< table>] <backup_name>
   - new command that do : download, restore-schema, restore-data by default. 
   - Flags allow to skip some parts:
   - --skip-download
   - --skip-schema
   - --skip-data
1. freeze : deprecated (still useful ?)
1. create : deprecated (see backup)
1. upload : deprecated (see backup)
1. download : deprecated (see restore)
1. restore-schema : deprecated (see restore)
1. restore-data : deprecated (see restore)
1. clean : deprecated (see backup)

**Comment by AlexAkulov** [comment]
I like that 'create', 'upload', 'download' and 'restore' commands are separated. 
In my case create+upload are executed by cron and it is not necessary to make this command more simple, you write this only once. 
Support of s3 is additional feature. Some people use clickhouse-backup just for creating backup and don't upload it to cloud or use 'rsync' for copying backup to another server and never use embedded 'download' and 'upload' features, for them odd flags will appear.
When I use create backup manually for operations like rename table or before upgrade clickhouse I don't want to upload this backup. For this case I will have to add additional flags.
download+restore is very rare operation because usually you already have local backups. 
Sorry, but I think union create+upload and download+restore operations will complicate the usage.

'restore-schema' and 'restore-data' are separated in order you can create schema manually, but perhaps this is a rare case and these commands may be united. 

'freeze' is present because before ClickHouse v19.4.4.33 you could not freeze whole table easily, you had to freeze all parts of a table one by one. freeze had to be useful if you use custom scripts for backups. Maybe now it can be removed. 
'clean' is needed if you use 'freeze' or 'create' backup was interrupted or failed. Maybe it can be removed too.

**Comment by dcastanier** [comment]
Expecting that own problem is an universal problem is a natural bias for a developer.
Thank's for your clarification and your time.

**Comment by develar** [comment]
I can also add, that in my case I use `download` in init container for k8s, and then `restore-schema + restore-data` as part of clickhouse container (to ensure that clickhouse container will be not started until potentially slow downloading will be not performed).
