### ISSUE TITLE
can not  change destination data path

### ISSUE THREAD

**Issue by myabce** [Altinity/clickhouse-backup#617]
try to restore backup to another node，
source destination：/clickhouse/data/
target destination：/clickhouse-server/data/

but data was restored into /clickhouse-server/store。

**Comment by Slach** [comment]
Which is source clickhouse-server version and which is clickhouse-server destination server version?
Possible root cause Data restore to store cause your old clickhouse-server version doesn't store database engine inside metadata.json
and cause default database engine changed from Ordinary to Atomic 
so, /clickhouse-server/store this is default 

inside `/clickhouse-server/data/` you shall contains `/database/table/` as symlink to /clickhouse-server/store/XX/table_uuid/
