### ISSUE TITLE
Backup metadata for disaster recovery cluster

### ISSUE THREAD

**Issue by Shankara-git** [Altinity/clickhouse-backup#762]
We have deployed clickhoue cluster in kubernetes, includes 4 pods(2 shards and 2 replica). In our deployment data is stored at GCS bucket and we want to take backup only metadata part and reuse the data in GCS bucket.

Is there any suggestion for backup only metadata using clickhouse-backup?

Thanks

**Comment by Slach** [comment]
`clickhouse-backup create_remote --schema --rbac --configs`
will create backup only for all UDF, dictionaries, RBAC, configs from /etc/clickhouse-backup (if available) without data

**Comment by Shankara-git** [comment]
@Slach I have tried 'clickhouse-backup create_remote --schema --rbac --configs' command but it is not backing up metadata at /var/lib/clickhouse/disks/{disk_name}/store

**Comment by Shankara-git** [comment]
> `clickhouse-backup create_remote --schema --rbac --configs` will create backup only for all UDF, dictionaries, RBAC, configs from /etc/clickhouse-backup (if available) without data



@Slach I have tried 'clickhouse-backup create_remote --schema --rbac --configs' command but it is not backing up metadata at
/var/lib/clickhouse/disks/{disk_name}/store
/var/lib/clickhouse/metadata/{db}/{table}.sql
we are using GCS as a storage and we don't want to take backup of data again. so, we want to take backup of only metadata at /var/lib/clickhouse/disks/{disk_name}/store and /var/lib/clickhouse/metadata/{db}/{table}.sql

is it possible with clickhouse-backup ? or is it possible to use rclone command as a custom command is clickhouse-backup ?

Thanks

**Comment by Slach** [comment]
> and we want to take backup only metadata part and reuse the data in GCS bucket.

Looks like I misunderstood this phrase.

to allow backup object disks
you need define
```
gcs:
  path: /backup/{cluster}/{shard}
  object_disk_path: /object_disks_backup/{cluster}/{shard}  
```

you can't re-use exists GCS data, cause you can't guarantee object disk keys still exists during restore

clickhouse-backup 2.4+ implemented server side CopyObject execution to allow copy object disks during `create` command to `object_disk_path` without copy it to local server

**Comment by Slach** [comment]
> we are using GCS as a storage and we don't want to take backup of data again. so, we want to take backup of only metadata at /var/lib/clickhouse/disks/{disk_name}/store and /var/lib/clickhouse/metadata/{db}/{table}.sql

`db/table.sql` will backup anywhay to /var/lib/clickhouse/backup/backup_name/metadata/db/table.json

`/var/lib/clickhouse/disks/{disk_name}/store` is not enough for backup, because after background merges\mutations `clickhouse-sever` can delete keys in GCS which referenced in /var/lib/clickhouse/disks/{disk_name}/store/*.* files, or you can lose your data after `DROP TABLE db.table SYNC`


> or is it possible to use rclone command as a custom command is clickhouse-backup ?

you can try to make `rclone` shell wrapper, which will try to upload, but CopyObject disks content will execute before `upload` with `rclone` during `create` command

clickhouse-backup 2.3.x- make exactly what you want
it not, use CopyObject and will backup only local metadata, but this is no backup
