### ISSUE TITLE
How to do incremental backup?

### ISSUE THREAD

**Issue by svladykin** [Altinity/clickhouse-backup#81]
Subj.

**Comment by fassisrosa** [comment]
Could this be it?

clickhouse-backup upload [--diff-from=<backup_name>] <backup_name>

When uploading to S3? Interest in understanding how the incremental backup works as well...

Seems like it would upload only deltas from previous specified backup?

**Comment by fassisrosa** [comment]
If I understand code correctly, it's not that it does an incremental backup. What it does do is an incremental upload. backups are always full backups but when we upload the backup, diffs are performed and files that existed in previous upload are not uploaded. Only new ones.

As a result, when you call the 'download', required dependency uploaded backups are also downloaded. You end up with a sequence of backups downloaded and properly 'hard-linked' so that you have in your last backup a copy of all the files you started with.

That is what I think is happening by reading the code. Will wait for confirmation from author. I am testing this feature as well since I want to use it.

**Comment by fassisrosa** [comment]
Seemed to confirm this. Here is my example. 

Did a first backup:

`/tmp/clickhouse-backup -c /tmp/config.yml create lixo1`

Uploaded full:
`/tmp/clickhouse-backup -c /tmp/config.yml upload lixo1`

Data changes...

Do another one:
`/tmp/clickhouse-backup -c /tmp/config.yml create lixo2`

Uploaded with diffs:
`/tmp/clickhouse-backup -c /tmp/config.yml upload --diff-from lixo1 lixo2`

Data changes...

Do another one:
`/tmp/clickhouse-backup -c /tmp/config.yml create lixo3`

Uploaded with diffs:
`/tmp/clickhouse-backup -c /tmp/config.yml upload --diff-from lixo2 lixo3`

Now deleted all local backups:
```
/tmp/clickhouse-backup -c /tmp/config.yml delete local lixo1
/tmp/clickhouse-backup -c /tmp/config.yml delete local lixo2
/tmp/clickhouse-backup -c /tmp/config.yml delete local lixo3
```

Now try downloading lixo3:
`/tmp/clickhouse-backup -c /tmp/config.yml download lixo3`

Output:
```
root@clickhouse-data-2:/# clickhouse /tmp/clickhouse-backup -c /tmp/config.yml download lixo3
 0 / 3651 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
2020/03/04 17:44:10 Backup 'lixo3' required 'lixo2'. Downloading.
 0 / 3652 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
2020/03/04 17:44:10 Backup 'lixo2' required 'lixo1'. Downloading.
 14.21 KiB / 14.21 KiB [==================================================================================================================================================================] 100.00% 0s
 3.57 KiB / 3.57 KiB [====================================================================================================================================================================] 100.00% 0s
 3.57 KiB / 3.57 KiB [====================================================================================================================================================================] 100.00% 0s
 2020/03/04 17:44:11   Done.
```

Notice how lixo1 and lixo2 were also donwloaded.

Now if you crack open lixo3.tar.gz you will see a file called meta.json:
meta.json file:
```
{
	"required_backup": "lixo2",
	"hardlinks": [
		"shadow/my_db/my_table/f0efc9a00a7872fda0e9f9ec4ee8fc47_0_4_1/checksums.txt",
		"shadow/my_db/my_table/f0efc9a00a7872fda0e9f9ec4ee8fc47_0_4_1/columns.txt",
		... snipped ...
	]
}
```

And if you crack open lixo2.tar.gz you will see a file called meta.json:
```
{
	"required_backup": "lixo1", 	
	"hardlinks": [ 
		"shadow/my_db/my_table/f0efc9a00a7872fda0e9f9ec4ee8fc47_0_4_1/created_at.bin",
		"shadow/my_db/my_table/f0efc9a00a7872fda0e9f9ec4ee8fc47_0_4_1/created_at.mrk",
		... snipped ...		
	]
}
```

So these meta.json will keep track of files that are kept from previous backup.

Downside: you might need to download a LOT more data to restore a backup (if files existed in lixo2 and are gone in lixo3 you're still loading all files from lixo2 and lixo3 even the ones you are not using in lixo3).
Upside: you will upload a lot less data when doing a backup upload (if files exist in lixo2 they will not be uploaded with lixo3, just marked as such in meta.json).
Given that you will more often (I hope) be uploading (doing backups) than downloads (restoring), seems like a good compromise. 

Pretty cool stuff!

**Comment by AlexAkulov** [comment]
Thank you! 
This is completely correct description.

**Comment by svladykin** [comment]
@fassisrosa Thanks for the explanation!

Some more additional questions:

1. What will happen if I 

- created backup1
- applied some modifications
- dropped some partition X  
- created incremental backup2
- restored backup2

will I have partition X back or `clickhouse-backup` knows that it must be dropped from backup1 when it is applied as part of backup2?

2. Is that possible to have TTL aware backups? I mean the following sequence:

- create backup1
- create incremental backup2 
- create incremental backup3
- drop backup1 because I know that it has only outdated partitions at this moment
- create incremental backup4
- restore backup4 (starting with backup2 because we do not have backup1 anymore)

Or I have to periodically do full backups anyways?

**Comment by fassisrosa** [comment]
From my understanding this is what will happen (@AlexAkulov correct me if I'm wrong):

1. You will NOT have your partition X back if you restore backup2. This is what will happen.

   You create backup1, it includes partition X, Y and Z (their files). You do a full upload, all files go to remote storage.
   You drop partition X and create partition W. You create backup2. *if partition files for Y and Z are untouched, i.e. the same* the incremental upload will only upload files for partition W and will register in the metadata files that only files for partitions Y and Z are to be taken from backup1.
  You wipe out DB, download backup2 (due to metadata file, it will download backup1 as well). The backup2 files will contain files for partition W (the new ones) and will hard link to files for partitions Y and Z downloaded with backup1. 
  You restore backup2 from the downloaded local backup2, it only really contains files for partitions W, Y and Z (last two partition files hardlinked to files from backup1).
  Only partitions W, Y and Z will be restored.

2. You do need to periodically do full backup *uploads*.

    First start by noting that a *backup* is always a full backup. The upload operation is the one that can do a partial packaging and copying.

   Now look at previous explanation. Your incremental upload (backup2 above) will never contain all files. instead it will have the metadata outlining the dependency on files from another backup. The tool will need to download your backup (backup2) and all other backups it depends on transitively (backup1 and others backup1 might depend on). These other backups are the ones containing the files that were not included in backup2. So if you delete the first backups from which your backup depends on, you will not be able to restore. The last backups simply do not contain the files.
  To support backup TTL you will need to put in place a periodic full backup. Or keep all backups from the beginning of time, a bad idea since that will be a) a waste of storage space since most of this will be unneeded and b) really impractical restore operation as *all* backups from the beginning of time would need to be downloaded for a restore to happen (and the majority of downloaded files would be useless).

**Comment by svladykin** [comment]
@fassisrosa Thanks a lot for your help!

**Comment by knoguchi** [comment]
This should be incorporated to the README and the documents.

**Comment by cntsp** [comment]
Very Nice!
