### ISSUE TITLE
Incremental backup based on partition?

### ISSUE THREAD

**Issue by huliangshan** [Altinity/clickhouse-backup#990]
The target instance partition already exists. How to restore the backed up partition to the target instance partition incrementally? The current verification result is that it will overwrite the target partition？

backup restore log:

...
ALTER TABLE database.db  DROP PARTITION 202408 SETTINGS mutations_sync=2 
...

Will the original partition be deleted?

**Comment by Slach** [comment]
> The current verification result is that it will overwrite the target partition？

yes, this is expected behavior
during `clickhouse-backup restore --data --partition=XXX db.table` whole partition will be overwritten

> How to restore the backed up partition to the target instance partition incrementally?

this is have no sense, in common case 
you can't guarantee for Collapsing / Replacing MergeTree avoid duplicates

you can manually use something like that
`cp -fv -l /var/lib/clickhouse/backup/backup_name/shadow/db/table/default/<partition_name>* /var/lib/clickhouse/data/db/table/detached/`

and use `ALTER TABLE db.table ATTACH PARTITION '<partition_name>'`
but please training in staging environment before and check the data

**Comment by huliangshan** [comment]
@Slach 
Error occurred when logging in with admin：

ALTER TABLE db.table ATTACH PARTITION '<partition_name>'

Received exception from server (version 22.8.21):
Code: 481. DB::Exception: Received from localhost:9000. DB::ErrnoException. DB::ErrnoException: Cannot set modification time for file: /var/lib/clickhouse/store/638/63825081-d181-4f94-81fe-ad8387659999/detached/attaching_202408_0_0_0, errno: 1, strerror: Operation not permitted. (PATH_ACCESS_DENIED)

**Comment by Slach** [comment]
`chown clickhouse:clickhouse -R /var/lib/clickhouse/store/638/63825081-d181-4f94-81fe-ad8387659999/detached`

**Comment by huliangshan** [comment]
backup partition name: 202408_0_0_0

run  "alter table xxx attach partition '202408_0_0_0'" command log:


Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Cannot convert string 202408_0_0_0 to type UInt32. (TYPE_MISMATCH)

**Comment by huliangshan** [comment]
rename 202408_0_0_0 to 202408   run "alter table xxx attach partition '202408'"  is successful! 

0 rows in set!

It should be 15 pieces of data！

**Comment by huliangshan** [comment]
thank! 
change sql to  ”ALTER TABLE `db`.`table` ATTACH PART '202408_0_0_0'"  

Displaying 0 sets, actually imported successfully
